import * as t from '@/diet-server/diet.types'
import {ITEM_TYPES} from "@/diet-server/diet.constants";

const itemType = ITEM_TYPES.PRODUCT;

export const STOCK_PRODUCTS: t.StockStateNormalized<t.Product> = {
  allIds: [
    "øl03",
    "øl05",
    "Big100",
    "Manchego",
    "CottageCheeseOriginal",
    "Whey",
    "Whey_Double",
    "Egg",
    "CottageCheeseMager",
    "PeanutSmør",
    "Syltetøy",
    "Kesam_stor",
    "Kesam_liten",
    "Kesam_mager_stor",
    "Kesam_mager_liten",
    "FetaBoksOriginal",
    "FetaBoksMager",
    "PinjeKjerner",
    "Jalapenos",
    "KjøttdeigSvin",
    "RevetOst",
    "RømmeQDrømmelett",
    "TacoKrydder",
    "GuacamoleFerdigdip",
    "TortillaChips",
    "Kyllingfilet",
    "Svinekoteletter",
    "SvinIndrefilet",
  ],
  byIds: {
    "øl05": {
      type: itemType,
      id: "øl05",
      name: "øl05",
      protein: 0,
      calories: 200,
      grams: 100,
    },
    "øl03": {
      type: itemType,
      id: "øl03",
      name: "øl03",
      protein: 0,
      calories: 130,
      grams: 300,
    },
    "Big100": {
      type: itemType,
      id: "Big100",
      name: "Big100",
      protein: 30,
      calories: 393,
      grams: 100,
    },
    "Manchego": {
      type: itemType,
      id: "Manchego",
      name: "Manchego",
      protein: 40,
      calories: 688,
      grams: 150,
    },
    "CottageCheeseOriginal": {
      type: itemType,
      id: "CottageCheeseOriginal",
      name: "CottageCheeseOriginal",
      protein: 54,
      calories: 384,
      grams: 400,
    },
    "Whey": {
      type: itemType,
      id: "Whey",
      name: "Whey",
      protein: 20,
      calories: 100,
      grams: 30,
    },
    "Whey_Double": {
      type: itemType,
      id: "Whey_Double",
      name: "Whey Double",
      protein: 41,
      calories: 200,
      grams: 60,
    },
    "Egg": {
      type: itemType,
      id: "Egg",
      name: "Egg",
      protein: 7,
      calories: 80,
      grams: 60,
    },
    // Other products
    // Note: I have used the ids directly as given, please ensure they are unique for each product
    "CottageCheeseMager": {
      type: itemType,
      id: "CottageCheeseMager",
      name: "CottageCheeseMager",
      protein: 52,
      calories: 316,
      grams: 400,
    },
    "PeanutSmør": {
      type: itemType,
      id: "PeanutSmør",
      name: "PeanutSmør",
      protein: 3.6,
      calories: 91,
      grams: 15,
    },
    "Syltetøy": {
      type: itemType,
      id: "Syltetøy",
      name: "Syltetøy",
      protein: 0,
      calories: 0,
      grams: 15,
    },
    "Kesam_stor": {
      type: itemType,
      id: "Kesam_stor",
      name: "Kesam",
      protein: 24,
      calories: 468,
      grams: 400,
    },
    "Kesam_liten": {
      type: itemType,
      id: "Kesam_liten",
      name: "Kesam",
      protein: 18,
      calories: 351,
      grams: 400,
    },
    "Kesam_mager_stor": {
      type: itemType,
      id: "Kesam_mager_stor",
      name: "Kesam",
      protein: 38,
      calories: 256,
      grams: 400,
    },
    "Kesam_mager_liten": {
      type: itemType,
      id: "Kesam_mager_liten",
      name: "Kesam",
      protein: 28,
      calories: 192,
      grams: 300,
    },
    "FetaBoksOriginal": {
      type: itemType,
      id: "FetaBoksOriginal",
      name: "FetaBoksOriginal",
      protein: 26,
      calories: 480,
      grams: 200,
    },
    "FetaBoksMager": {
      type: itemType,
      id: "FetaBoksMager",
      name: "FetaBoksMager",
      protein: 0,
      calories: 0,
      grams: 200,
    },
    "PinjeKjerner": {
      type: itemType,
      id: "PinjeKjerner",
      name: "PinjeKjerner",
      protein: 9.5,
      calories: 351,
      grams: 50,
    },
    "Jalapenos": {
      type: itemType,
      id: "Jalapenos",
      name: "Jalapenos",
      protein: 0,
      calories: 12,
      grams: 120,
    },
    "KjøttdeigSvin": {
      type: itemType,
      id: "KjøttdeigSvin",
      name: "KjøttdeigSvin",
      protein: 72,
      calories: 576,
      grams: 400,
    },
    "RevetOst": {
      type: itemType,
      id: "RevetOst",
      name: "RevetOst",
      protein: 95,
      calories: 1540,
      grams: 500,
    },
    "RømmeQDrømmelett": {
      type: itemType,
      id: "RømmeQDrømmelett",
      name: "RømmeQDrømmelett",
      protein: 24,
      calories: 279,
      grams: 300,
    },
    "TacoKrydder": {
      type: itemType,
      id: "TacoKrydder",
      name: "TacoKrydder",
      protein: 5.2,
      calories: 126,
      grams: 40,
    },
    "GuacamoleFerdigdip": {
      type: itemType,
      id: "GuacamoleFerdigdip",
      name: "GuacamoleFerdigdip",
      protein: 5,
      calories: 307,
      grams: 250,
    },
    "TortillaChips": {
      type: itemType,
      id: "TortillaChips",
      name: "TortillaChips",
      protein: 14,
      calories: 940,
      grams: 200,
    },
    "Kyllingfilet": {
      type: itemType,
      id: "Kyllingfilet",
      name: "Kyllingfilet",
      protein: 216,
      calories: 936,
      grams: 900,
    },
    "Svinekoteletter": {
      type: itemType,
      id: "Svinekoteletter",
      name: "Svinekoteletter",
      protein: 450,
      calories: 2178,
      grams: 900,
    },
    "SvinIndrefilet": {
      type: itemType,
      id: "SvinIndrefilet",
      name: "SvinIndrefilet",
      protein: 132,
      calories: 690,
      grams: 600,
    },
  }
}
