const THEME = {
  extend: {
    colors: {
      bg1: 'var(--background)',
      fg1: 'var(--foreground)',
      accent1: 'var(--accents-1)',
      accent2: 'var(--accents-2)',
      accent3: 'var(--accents-3)',
      accent4: 'var(--accents-4)',
      accent5: 'var(--accents-5)',
      accent6: 'var(--accents-6)',
      accent7: 'var(--accents-7)',
      accent8: 'var(--accents-8)',
      selection: 'var(--selection)',
      secondary: 'var(--secondary)',
      code: 'var(--code)',
      border: 'var(--border)',
      error: 'var(--error)',
      errorLighter: 'var(--error-lighter)',
      errorLight: 'var(--error-light)',
      errorDark: 'var(--error-dark)',
      success: 'var(--success)',
      successLighter: 'var(--success-lighter)',
      successLight: 'var(--success-light)',
      successDark: 'var(--success-dark)',
      warning: 'var(--warning)',
      warningLighter: 'var(--warning-lighter)',
      warningLight: 'var(--warning-light)',
      warningDark: 'var(--warning-dark)',
      cyan: 'var(--cyan)',
      cyanLighter: 'var(--cyan-lighter)',
      cyanLight: 'var(--cyan-light)',
      cyanDark: 'var(--cyan-dark)',
      violet: 'var(--violet)',
      violetLighter: 'var(--violet-lighter)',
      violetLight: 'var(--violet-light)',
      violetDark: 'var(--violet-dark)',
      purple: 'var(--purple)',
      alert: 'var(--alert)',
      magenta: 'var(--magenta)',
      link: 'var(--link)',
    },
    boxShadow: {
      dropdown: 'var(--dropdown-box-shadow)',
      small: 'var(--shadow-small)',
      medium: 'var(--shadow-medium)',
      large: 'var(--shadow-large)',
    },
    // You can add other properties like textColor, borderColor, etc.
  }
};

module.exports = { THEME };
