name: Test firestore on push to master or main
'on':
  push:
    branches:
      - master
      - main
jobs:
  test-firestore:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '16'
      - run: npm install -g firebase-tools
      - run: yarn install --frozen-lockfile
      - run: echo "Here is where i start the emulator hihi :)"

