name: Test Firestore on push to master
'on':
  push:
    branches:
      - master
      - main
jobs:
  test_rules:
    runs_on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12'
      - run: npm install -g firebase-tools
      - run: npm ci
      - run: echo "Here is where i start the emulator hihi :)"

